- `Vocabulary(V)`: This consists of all the unique words present in the corpus.
- `Corpus( C )`: All the text data or records of the dataset together are known as a corpus. e.g book
- `Document(D)`: One single text record of the dataset is a Document. e.g page or paragraph
- `Word(W)`: The words present in the vocabulary. e.g. a word

### 2. **Text Representation**
- convert text into machine readable format
    - BoW
    - Tf-idf
    - Word Embeddings
    - Sentence Embeddings

- the llms are capabale of advanced analysis of text, prompts and of generating text that is conversational
- if you want to understand how things work in LLMs, how chat GPT like models talk like humans, you will need to start at the basics of NLP
- Text preprocessing 
    - why we teach first?
    - it tells you that you can deal with text using some coding techniques
- Text Representation 
    - how you would make a computer understand text
    - THe first of its kind was:
        - Character Encoding

### **Character Encoding** (ASCII and UTF-8)
- we have a way of telling computers that these are letters - `abcdef` or characters - `apiournaonrapnurjnaunbu*^$#$^%^(%#(%*%^&))`
- Computers only understand `110101001010101010101`
- We have Boolean Logic, and Number Systems to help convert the `1010101010` the `364674` --- (`1010`)bin = (`10`)dec
- when you hit `A` ---> your computer sees `65`
- ASCII is an international standard of encoding characters
    - `A` = 65. `B` = 66
    - 7 bits for character encoding - used to be stored on 8-bit (1 byte) encoding scheme
    - 1 bit just there
    - _ _ _ _ _ _ _ _ = 2**7 = 128
    - this many characters were encoded
    - (A - z, a - z), (0 -9), basic punctuations
    - this did not support emojis, special characters, non english scripts
    - 
- Unicode Transformation Format - `UTF-8`
    - modern standard for web or python3
    - it is `variable width`
    - it uses 1 byte for standard english, which makes it compatible with ASCII as well
    - upto the first 4 bytes include all characters including emojis

- UTF-16 `2 to 4 bytes`, UTF-32 `fixed 4 bytes`

In [96]:
letters = ['A','B','C', 'a', 'b', 'c','!','@','#']
chr(0)
for letter in letters:
    ASCII_code = ord(letter)
    print(f"ASCII of {letter} ---> {ASCII_code}")

ASCII of A ---> 65
ASCII of B ---> 66
ASCII of C ---> 67
ASCII of a ---> 97
ASCII of b ---> 98
ASCII of c ---> 99
ASCII of ! ---> 33
ASCII of @ ---> 64
ASCII of # ---> 35

In [50]:
letter = '😊'
encoded_letter = letter.encode('utf-8')
encoded_letter
# type(encoded_letter)

# encoded_letter.decode()

b'\xf0\x9f\x98\x8a'

**Label Encoding - One Hot Encoding**
- transformed catagories into binary values
- e.g. multiple categories in Iris, each instance got a vector representation
    - species = iris `setosa` [0] ---> `[1, 0, 0]`
    - species = iris `virginica` [1] ---> `[0, 1, 0]`
    - species = iris `versicolor` [2] ---> `[0, 0, 1]`

## **$$Text-Representation$$** 
- is the process of **converting** human language into **numerical formats** that machines can understand and process

- Conversion of `strings` to ` series of numbers` ---> `VECTORIZATION`
    - vectors are simply `columns`, `features`, single dimension matrix
    -

### Bag of Words
- describes the ocurrence of words within a document completely ignoring the order (or grammer)
- is one of the simplest text representations
- counts how many times a word appears in a document

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "Forests are green and beautiful.",
    "Green trees make a forest beautiful"
]

vectorizer = CountVectorizer()
bow_matrix = vectorizer.fit_transform(corpus)

bow_matrix.toarray()
vectorizer.get_feature_names_out()

import pandas as pd

df = pd.DataFrame(bow_matrix.toarray(), columns=vectorizer.get_feature_names_out())
df

   and  are  beautiful  forest  forests  green  make  trees
0    1    1          1       0        1      1     0      0
1    0    0          1       1        0      1     1      1

### TF-IDF (TERM FREQUENCY - Inverse Document Frequency)
- A statistical measure that evaluates the importance of a word in a document relative to a collection of documents(corpus)
- 
- It rewards the words that appear a lot in a specific `document` across the `corpus` ---> Term Frequency
- ![](https://media.geeksforgeeks.org/wp-content/uploads/20250207113146020518/The-TF-Formula.webp)
- it heavily penalizes words that appear in every document ---> Inverse Document Frequency
- penalizes more frequency
- ![](https://media.geeksforgeeks.org/wp-content/uploads/20250207113218469447/IDF-Formula.webp)
- Number of documents in the corpus
- 
- We are analyzing 1000 articles ---> corpus
    - `the` appears everywhere in all the corpus so tf-idf ---> score of 0
    - word `Jedi` appears 40 times in a specific article
    - tf-idf will give it a massive score to say that this word is very important for the document

In [ ]:
corpus = [
    "Forests are green and beautiful.",
    "Green trees make a forest beautiful"
]

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

tf_idf = TfidfVectorizer()

tf_idf_matrix = tf_idf.fit_transform(corpus)
# pd.DataFrame(tf_idf_matrix.toarray(), columns =tf_idf.get_feature_names_out())
# tf_idf.get_feature_names_out().shape

# multiplication of the tf idf in every place --> normalization ---> values exist 0 to 1
# 

idfs = tf_idf.idf_
words = tf_idf.get_feature_names_out()

# pd.DataFrame(idfs.T, columns= words)

word_idfs = (zip(words, idfs))

for i, x, in word_idfs: # unpacking zips
    print(i , x)

and 1.4054651081081644
are 1.4054651081081644
beautiful 1.0
forest 1.4054651081081644
forests 1.4054651081081644
green 1.0
make 1.4054651081081644
trees 1.4054651081081644

- **Document Similarity and Clustering**: By converting documents into numerical vectors TF-IDF enables comparison and grouping of related texts. This is valuable for clustering news articles, research papers or customer support tickets into meaningful categories.
- **Text Classification:** It helps in identify patterns in text for spam filtering, sentiment analysis and topic classification.
- **Keyword Extraction**: It ranks words by importance making it possible to automatically highlight key terms, generate document tags or create concise summaries.
- **Recommendation Systems**: Through comparison of textual descriptions TF-IDF supports suggesting related articles, videos or products enhancing user engagement.

- mini search engine based on this

## Word Embeddings
- Continous mathematical vectors that capture the semantic meaning, context, and relationship of words
- Method of extracting features out of text so that we can input those features into a machine learning model
- Allows words with similar meanings to have a similar representation.
- Similarity can be assessed based on Similar vector representations.
- 
![](https://media.geeksforgeeks.org/wp-content/uploads/20250530170636975663/Embeddings-in-Natural-Language-Processing.webp)

![](https://media.geeksforgeeks.org/wp-content/uploads/20250530170636672412/Techniques-in-Embeddings-in-NLP.webp)

- instead of counting words, we could plot them as coordinates on a giant multidimension graph (300 dimensions)
- the closer those lines are in space, the similar their meanings would be
- 
- this can literally help us do the math for
    - King ~ Man
    - Queen ~ Woman
    - expression : King - Man + Woman = Queen
    - words like Dog ~ Puppy
    -

In [87]:
# pip install spacy

In [95]:
# !python -m spacy download en_core_web_md

In [94]:
import spacy # another famous NLP library

nlp = spacy.load("en_core_web_md")

word1 = nlp("King")
word2 = nlp("Queen")
word3 = nlp("man")
word4 = nlp("woman")

print("similarity score King : man", word1.similarity(word3))
print("similarity score King:woman ", word1.similarity(word4))
print("similarity score King:Queen ", word1.similarity(word2))
print("similarity score Queen:woman ", word2.similarity(word4))

similarity score King : man 0.3676641285419464
similarity score King:woman  0.22016216814517975
similarity score King:Queen  0.38253092765808105
similarity score Queen:woman  0.6170459985733032

Most popular word embedding models: 
### 1. **Word2Vec**
- learns to represent words as vectors in a way that captures their meaning based on context in the corpus
- Word2Vec looks at the whole corpus at once
- it is predictive
- it uses a shallow neural network to learn word meanings, by playing a guessing game with the context
- it does not know the context, just guesses
- you shall know a word by the company it keeps
    1. **Continous Bag of Words** 
    - predicts a **8** word based on the **surrounding** **context** words
    - give the model **context words** : the cat _____ the mat
    - model will try to predict the **target word**: ________sat_______
    - e.g. the cat *sits* on the mat
        - sits target --- the cat --- the mat --- context words


    2. **Skip Gram**
    - predicts **surrounding context words** from a **target word**
    - opposite of CBoW
    - give model **context words**, tries to predict the **target word**
    - 
![](https://swimm.io/wp-content/webp-express/webp-images/uploads/2023/11/word2vec--1024x559.png.webp)


- 
- it uses a neural network, we don't care about the output, we care about the weights of the hidden layer
- these **weights** are the **word embedding**
-

In [98]:
# pip install gensim

In [107]:
from gensim.models import Word2Vec # anothe famous libarary for NLP
from nltk.tokenize import word_tokenize
import nltk

corpus = [
    "Machine learning is a subset of artificial intelligence",
    "Python is the most popular language for data science",
    "Neural networks are the backbone of deep learning",
    "Data science involves statistics and programming"
]

# we don't want to take the whole corpus, and turn it into tokens
token_sentences = [word_tokenize(sentence.lower()) for sentence in corpus]

# train word2vec
model = Word2Vec(
    sentences = token_sentences,
    vector_size = 100, # 100 numbers per word --- shape of the vector
    window = 5,        # how many words to look at 
    min_count = 1,      # ignore words that appear this many times
    workers = 4         # model uses 4 threads simulataneously -- 4 CPU cores
)
# computations will be small ---> there will be a lot of them 
# you have vectors of dimensions 100 - operations 
# parallel processing --- 
# the sweet spot will be between 3 to 12 workers --- the way the data moves, setting
# worker number as higher, might slow things down
# If you need reproducibility ---> workers = 1

# find words similar to any word --- python
similar_words = model.wv.most_similar('python')
similar_words

# actual vector of the word
vector = model.wv['python']
vector[:5]

array([ 0.00562671,  0.00549737,  0.00182912,  0.00574941, -0.00896808],
      dtype=float32)

- This vector ---> Dense vector ---> word embedding

### 2. **GloVe (Global Vectors for Word Representation)**
- word embedding technique
- analyses global co-occurences of words in a corpus ---> to create word vectors
- Word2Vec  focuses on local context (neighbouring words)
- GloVe focuses on global statistics of the corpus
- ![](https://th.bing.com/th/id/OIP._Aap0YgGccqfpGmADIL0lgHaHT?rs=1&pid=ImgDetMain)
- King - man + woman = queen
- Capture relationships using mathematical operations

implementation is a little different from Word to Vec, 
- you **train** **word2Vec** models, **GloVe** is mostly always used as a **pretrained** embeddings

-

In [ ]:
import gensim.downloader as api

model = api.load("glove-wiki-gigaword-50")
# dimensions === 50

In [ ]:
# King - man + woman = queen
result = model.most_similar(positive = ['king', 'woman'], negative= ['man'], topn=1)
result

[('queen', 0.8523604273796082)]

In [124]:
# check similarity scores
model.similarity('python', 'programming')

# find an odd one out
words = ['python', 'java', 'c++', 'broccoli']
words = ['python', 'java', 'c++', 'tomato', 'C', 'javascript']
model.doesnt_match(words)

'tomato'

In [136]:
# vectors of words
model['python'].shape

words = ['python', 'java', 'c++', 'tomato', 'javascript']

vector_Data = {word: model[word] for word in words}
vector_df = pd.DataFrame(vector_Data).T

vector_df.iloc[:,:5]

                   0        1         2        3         4
python      0.589700 -0.55043 -1.010600  0.41226  0.573480
java        1.028000 -1.52260  0.181320  1.28240 -0.438720
c++        -0.093207 -0.77116  0.036695  0.63591 -0.014505
tomato      0.237090 -0.49856 -1.079200  0.44938  0.651290
javascript  0.266790 -0.90822  0.124840  0.59276 -0.521610

model name | dimensions | trained on | size
---|---|---|----
glove-wiki-gigaword-50 | 50 | wikipedia 2014 | ~ 66MB
glove-twitter-25 | 25 | 2B Tweets | ~30MB
glove-wiki-gigaword-100 | 100 | wikipedia 2014 | ~ 128MB

In [112]:
info = api.info()

for model_name in info['models'].keys():
    print(model_name)

fasttext-wiki-news-subwords-300
conceptnet-numberbatch-17-06-300
word2vec-ruscorpora-300
word2vec-google-news-300
glove-wiki-gigaword-50
glove-wiki-gigaword-100
glove-wiki-gigaword-200
glove-wiki-gigaword-300
glove-twitter-25
glove-twitter-50
glove-twitter-100
glove-twitter-200
__testing_word2vec-matrix-synopsis

### 3. Named Entity Recognition (NER)
- identify entities like names, dates, etc

### 4. Syntactic Analysis
- analyse the grammatical structure of text
    - PoS Tagging
    - Dependency Parsing
    - Constituency Parsing